## ----------------------------------------------------------------------------
## ..:: Mysql POD / Service Configuration ::..
##-----------------------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: e-commerce
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: e-commerce
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: Default1234!
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: e-commerce-persistent-storage
          mountPath: /var/lib/mysql
          subPath: e-commerce/mysql
      volumes:
      - name: e-commerce-persistent-storage
        persistentVolumeClaim:
          claimName: e-commerce-pvc
