## ----------------------------------------------------------------------------
## ..:: BIG-IP CIS Secret for Management Username and Password ::..
## ----------------------------------------------------------------------------
##
## Please do a base64 of your BIG-IP username and password
##
## echo -n 'admin' | base64
## echo -n 'your-bigip-password-here' | base64
##
## ----------------------------------------------------------------------------
apiVersion: v1
kind: Secret
metadata:
  name: bigip-login
  namespace: ingress-services
data:
  username: YWRtaW4=
  password: RGVmYXVsdDEyMzQh
---
## ----------------------------------------------------------------------------
## ..:: BIG-IP CIS Service Account ::..
## ----------------------------------------------------------------------------
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bigip-ctlr
  namespace: ingress-services
---
## ----------------------------------------------------------------------------
## ..:: BIG-IP CIS ClusterRole ::..
## ----------------------------------------------------------------------------
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bigip-ctlr-clusterrole
rules:
- apiGroups: ["", "extensions", "networking.k8s.io"]
  resources: ["nodes", "services", "endpoints", "namespaces", "ingresses", "pods", "ingressclasses"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["", "extensions", "networking.k8s.io"]
  resources: ["configmaps", "events", "ingresses/status", "services/status"]
  verbs: ["get", "list", "watch", "update", "create", "patch"]
- apiGroups: ["cis.f5.com"]
  resources: ["virtualservers","virtualservers/status", "tlsprofiles", "transportservers", "ingresslinks", "externaldnss"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: ["fic.f5.com"]
  resources: ["f5ipams", "f5ipams/status"]
  verbs: ["get", "list", "watch", "update", "create", "patch", "delete"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "watch", "update", "create", "patch"]
- apiGroups: ["", "extensions"]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
---
## ----------------------------------------------------------------------------
## ..:: BIG-IP CIS ClusterRoleBinding ::..
## ----------------------------------------------------------------------------
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bigip-ctlr-clusterrole-binding
  namespace: ingress-services
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bigip-ctlr-clusterrole
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: bigip-ctlr
  namespace: ingress-services